name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest  # Using a GitHub-hosted runner

    container:
      image: termux/termux-docker:x86_64
      options: --user root

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          echo "TERM=xterm" >> $GITHUB_ENV

      - name: Check DNS readiness
        run: |
          echo "Checking DNS readiness..."
          max_attempts=$((2 * 60 / 5))
          attempt=1
          while [ $attempt -le $max_attempts ]; do
              if curl -Is https://termux.dev > /dev/null; then
                  echo "DNS is ready and HTTP request to Termux was successful."
                  break
              else
                  if [ $attempt -eq $max_attempts ]; then
                      echo "Timeout reached. DNS is still not ready."
                      exit 1
                  fi
                  attempt=$((attempt + 1))
                  sleep 5
              fi
          done

      - name: Update packages
        run: |
          sudo apt-get update -y

      - name: Run the metasploit installation script and check msfconsole version
        run: |
          ./metasploit.sh

      - name: Verify Metasploit version
        run: |
          msfconsole -v
