name: container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    # container:
    #   image: termux/termux-docker:x86_64
    #   options: --user root --entrypoint /entrypoint_root.sh
    steps:
         - name: test docker
           run: |
              docker run -it --rm ubuntu bash
              apt update
              apt install curl -y
         - name: check resolv
           run: cat $PREFIX/etc/resolv.conf
         - name: wait dns
           run: |
              ping -c 4 1.1.1.1
         - name: Log the node version
           run: |
              uname -a
              curl -O -fsSL https://raw.githubusercontent.com/gushmazuko/metasploit_in_termux/feature/github-actions/metasploit.sh
              bash metasploit.sh