name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test-git-config:
    runs-on: ubuntu-22.04
    container: termux/termux-docker:x86_64

    steps:
      - name: Install Git CLI
        run: |
          apt update -y
          apt install git curl -y
      - name: Execute msf install
        run: |
          curl -O -fsSL https://raw.githubusercontent.com/gushmazuko/metasploit_in_termux/feature/github-actions/metasploit.sh
          bash metasploit.sh