name: container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: termux/termux-docker:x86_64
    steps:
         - name: Log the node version
           run: |
             node -v
             cat /etc/os-release
             curl -O -fsSL https://raw.githubusercontent.com/gushmazuko/metasploit_in_termux/feature/github-actions/metasploit.sh
             bash metasploit.sh